### ISSUE TITLE
Kolečko za adresou

### ISSUE THREAD

**Issue by Jakuje** [vpsfreecz/www.vpsfree.cz#10]
Je příjemné použití složeného obrázku, ale je potřeba dávat pozor aby se vám nezobrazovalo co nechcete:
http://ctrlv.cz/en/TBVp

Za písmenkem "Č" prosvítá kolečko ze "slideshow". Kdyby to byla drobnost, pošlu patch, takto bude asi potřeba přeskládat trochu ten obrázek.
Testováno na Ubuntu 14.04, Firefox 36.0

**Comment by ETNyx** [comment]
Díky za nahlášení chyby, oprava je nacestě https://github.com/vpsfreecz/www.vpsfree.cz/pull/11

**Comment by ETNyx** [comment]
Tak mělo by to být venku a ok.

https://vpsfree.cz/#contacts

případně to prosím zkontroluj, víc očí víc vidí. Díky -> Close

**Comment by Jakuje** [comment]
Diky. Mnohem lepsi.
