### ISSUE TITLE
Přihláška - obludný formulář

### ISSUE THREAD

**Issue by vsigler** [vpsfreecz/www.vpsfree.cz#14]
První issue ke dotvoření webu - formulář k přihláce.

Z community listu:

> Proč musí být přihláška hned na hlavní straně a zabírat tolik místa? To je naprostej pseudo hyper form, který hejtuju už ze samého principu - nejen že je ošklivej a složitej a ve dvou sloupcích by zabral polovinu místa, ale na titulce má být prostě konverzní tlačítko “vyplnit přihlášku” a ten form tam nemusí být (věřím i tomu, že prostě dost lidí odradí jen ten).
> 
> Opravdu se na mě nezlobte, ale všichni jsou v pořádku s tím, že přihláška zabírá tolik místa? To je tak těžký udělat modal box na tlačítko? (já to teď klidně udělám, ale potřebuji vědět, že to je ta cesta, ať jen nekecám a ostatním nedávám karty na stůl).

K tomu se připojuji, formulář přihlášky se mi také nelíbí. Stejně široká políčka v úzkém sloupci působí dost nepřehledně a jako návštěvníkovi mi to říká "nechtělo se nám dělat se s formulářem, tak jsme to naházeli pod sebe". To pak může mít za následek "tldf" - too long, did not fill.
### Zobrazení

Návrh je tedy udělat formulář do modálního okna a na stránku jen tlačítko. Tlačítko v horní liště by také mohlo rovnou zobrazit ten formulář.
### Layout

Rozhodně ne úzký sloupec. Ten může být tak v mobilní verzi, ale na desktopu mám 16:9 obrazovku, proč tedy to místo nevyužít? Dál si myslím, že to chce formulář zjednodušit:
- Oddělit povinná políčka od volitelných
- Realistické velikosti polí - do PSČ nebudu psát přeci román
- Povinných co nejméně (např. je rok narození nutnost? Z pohledu většiny lidí do toho nikomu nic není)

**Comment by tomassrnka** [comment]
> Povinných co nejméně (např. je rok narození nutnost? Z pohledu většiny lidí do toho nikomu nic není)

Ad, povinne policka, okrem poslednych dvoch (Jak ses o nas dozvedel a poznamka) su povinne vsetky. Datum narodenia je od toho, ze clen musi mat nad 18 rokov (ak je pod 18 rokov, tak sa dotatocne jeho clenstvo kontroluje u zakonneho zastupcu) a je to istym sposobom kontrola nad "fake" prihlaskami. 

> "nechtělo se nám dělat se s formulářem, tak jsme to naházeli pod sebe"

S tym nesuhlasim, policka su rovnako siroke z dizajnoveho hladiska, uznavam, ze pohladu UX to nie je najlepsie riesenie, ale bol to zamer, nie chyba. 

Ci prihlasku prehodit do modal okna - o tom treba rozhodnut, za seba som proti. Modal okna funguju dost katastrofalne na mobilnych browseroch a som rad, ze je to takto v stranke ako klasicky formular.

**Comment by vsigler** [comment]
> Ci prihlasku prehodit do modal okna - o tom treba rozhodnut, za seba som proti. Modal okna funguju dost katastrofalne na mobilnych browseroch a som rad, ze je to takto v stranke ako klasicky formular.

Na mobilu se to klidně může zobrazit takto, tam je to přijatelné. Není snad ale problém mít to na dektopu jinak než na mobilu, ne?

**Comment by tomassrnka** [comment]
To nie samozrejme problem, ja vsak nevidim vyznam v tom, ked je stranka ako one-pager robit modal okno. Kludne nech sa vyjadria aj ostatni - ak su za, nech sa prihlaska hodi v desktop verzii do modal okna.

**Comment by blahout** [comment]
Nemusí to být modal, klidně se to může JS zobrazit jako div pod tlačítkem po kliku. Cílem je prostě nemít ten obludný form na titulní stránce, zabírá zbytečné místo. Určitě bych to rozdělil na dva sloupce. Bavme se tu o desktopové verzi, když se s tím bude počítat, bude to všechno responsivní a na mobilech se to naháže za sebe.

**Comment by vsigler** [comment]
Modal okno je návrh, zbytek je na diskusi.

Netvrdím, že to tak nutně musí být. :)

Řekl bych, že to důležité je "na desktopu ne sloupec na pětinu šířky stránky".

**Comment by blahout** [comment]
Když se to hodí šikovně do dvou sloupců, zabere to už tak polovinu své výšky a ještě to šikovně schovat. Já se nebráním žádnému pop-up oknu, dneska se to používá tak často, že to i na mobilech může fungovat.

**Comment by alpracka** [comment]
Rozhodne-li se modal, můžu doporučit třeba http://dimsemenov.com/plugins/magnific-popup/, umí to pěkně i na mobilu.

**Comment by lunemec** [comment]
Za me:

Odebrat zbytecna policka:
- prezdivka?? 
- poznamka? 
- distro (na to je snad admin ne?)? 
- Lokace vps (admin)?
- Stat ? - cz/sk, stejne jsou stranky v CZ only, takze asi vybiratko CZ/SK ktere rovnou urci menu CZK nebo EUR... a tim padem odpadne policko forma platby.

Hodit do 2 sloupcu. Zadny modal, kdyz bude ve sloupcich bude vypadat fajn.

Pridal bych jeste googli checkovatko antispamu (i'm not a robot).

Tady je nahled co jsem tam narychlo nahekoval:
![test](https://cloud.githubusercontent.com/assets/1670632/6509163/c54ad0c2-c35d-11e4-9acb-10dc7f0839e9.png)

**Comment by blahout** [comment]
Nebe a dudy (y) za mě určitě lepší, tak nebo tak bych to hodil pop-up nebo úplně na konec (jen ten form) a tlačítkem dojížděl do toho boxu až pod kontakty. To se mi zdá jako nejlepší řešení. V tom bloku mít jen tlačítko "vyplnit přihlášku" a tenhle celý blok hodit za kontakt. Proč? Když si vezmu, že ne všichni budou noví členové, ale budou jen hledat číslo účtu nebo tak a budou scrollovat nepůjdou přes menu, tak zešílí.

**Comment by blahout** [comment]
Jo a trochu bych zvětšil odsazení textfieldů a ten textbox bych hodil na šírku obou sloupců.

**Comment by vsigler** [comment]
Jo, takhle to vypadá rozhodně líp. Jako alternativa k popupu či umístění na konci může být ještě schovaný div, který po stisku tlačítka "vyjede", ale pokud se chceme těmhle věcem vyhnout, tak to umístění na konci je asi nejrozumnější.

**Comment by snajpa** [comment]
Jak jste prisli na to, ze jsou tam nejaky policka zbytecny? :) Kdyby byly, tak tam nejsou, jsou tam potreba, vsechny, jak tam jsou.

**Comment by snajpa** [comment]
Jinak s tlacitkem na zobrazeni toho formulare souhlasim, to je dobrej napad.

**Comment by vsigler** [comment]
To mi řekni, na co je pro vpsfree klíčový například rok narození členů? :) Zrovna tohle bych vnímal jako něco, do čeho nikomu nic není. Někdo to může vnímat negativně.

Přezdívka se dá vyřešit nějakou implicitní (JménoPříjmení) s tím, že by se povolila její jednorázová změna. Třebas, jen brainstorming.

Měna mi tam opravdu přijde zbytečná - buď pošlu v korunách na český účet nebo v eurech na slovenský.

Psal někdy někdo něco do poznámek, co by mělo pro registraci význam?

**Comment by snajpa** [comment]
At si to nekdo negativne vnima, pro nas je to uzitecna informace, ktera dost mluvi o tom, kdo se k nam hlasi.

Zrovna tak prezdivka, lidi chteji mit svoji.

Mena tam musi bejt, protoze to chceme vedet.

Poznamky lidi vcelku casto pouzivaji.

A vyber distribuce je tam potreba taky, protoze se rovnou vytvari VPS.

Jeste neco? ...

**Comment by vsigler** [comment]
Výběr distribuce nerozporuju.

Promiň, ale dávat tam políčka jen proto, že to chceme do statistiky? Chceme lidi prudit nebo nalákat?

**Comment by snajpa** [comment]
No, jak to napsat a nebejt zas za hejtujiciho debila :)

Ty veci jsou tam proste potreba, ty prihlasky neschvalujes, tak nevis. A neni to jenom kvuli statistice. Podle veku hned poznam, jakou uroven mam cekat - a dost to ve vetsine pripadu sedi. Jak vidim rok narozeni 1998+, znamena to nastrazeny usi-oci, protoze potencialni problemy s hernima serverama a podobne.

S tim, kolik je policek v prihlasce, se proste hejbat nebude. :)

**Comment by snajpa** [comment]
Jestli by melo cenu s necim hejbat v tom formulari, tak by bylo dobry dodelat rozliseni pravnicka/fyzicka osoba a pripadny zobrazeni danejch relevantnich policek navic - ale na to je potreba nejdriv dodelat to rozliseni do vpsAdminu.

Ty udaje z prihlasky jdou totiz rovnou do vpsAdminu, kterej nam posle mail, staci nam kliknout na 'approve' nebo 'deny' a tim mame vyreseno, clen rovnou dostava account s hotovou VPS, my v prihlasce mame dost informaci k jejimu posouzeni, vsichni jsou spokojeny. Nevidim duvod menit.

**Comment by vsigler** [comment]
:D Ok, beru. Tohle využití věku mě nenapadlo.

Pokud je to tedy s údaji z formuláře takhle, tak zbývá alespoň ten layout trochu zefektivnit.

**Comment by snajpa** [comment]
A to jsme tam puvodne meli cely datum narozeni, ale slevili jsme z nej, ze nam staci akorat rok. :)

**Comment by lunemec** [comment]
Ok, takze myslim ze jsme se uspesne vyvinuli do finalni podoby:
- schovavani formulare a ukazani na rozklik
- policka zustanou v aktualnim poctu
- rozdeli se do 2 rad?

Mam to takhle zkusit naflakat a postnout screen? Klidne udelam pull request, ale nejsem webmaster, takze to je <table> a <center> protoze me nezajima ze posrane prohlizece neco neumi a nechci to ani resit :) ale fungovat to bude :D

**Comment by snajpa** [comment]
Jj jen do toho, uplne souhlasim. Akorat bacha na to, ze ten web je responsive a je potreba si pohlidat chovani jeste i na tabletu a mobilu.

**Comment by blahout** [comment]
Za mě je to řešení:
- Vytvořit tlačítko "vyplnit přihlášku", které aktivuje ten div a zobrazí se form ve dvou sloupcích s tím že ten text box bych dal pod na šířku, ať to je nějak uživatelsky přístupné
- To rozdělení na dvě řady by taky mělo dávat smysl (Křestní jméno vlevo, příjmení vpravo atd.)
- Základní omyl UX je udělat form tak, aby mi poskytl max informací. Hlavní je aby ho člověk zvládnul vyplnit (pokud to tady má návaznost na systém, tak jako budiž, ale řešení to není)

**Comment by snajpa** [comment]
Az na to, ze tohle nema nic s UX, ty udaje proste chceme vedet. A na tom to stoji a pada, otazky UX jdou az nekde 10km po tom. Kdybychom ty veci nechteli vedet, tak tam nejsou.

**Comment by lunemec** [comment]
No tak jsem se 30 minut snazil to rozbehat pres PHP, a jelikoz ten jazyk bytostne nesnasim, tak musim s pokorou rict, ze na to nemam. Sorry, ale nechci se po vecerech vztekat a nadavat na po**ane PHP, nechci skoncit v blazinci :D

Samozrejme kdyz se zakomentuji PHP veci, jako je pripojeni k db a funkce na to navazane ktere tahaji neco z vpsfree DB tak se rozbije design, protoze to jsou preci 2 na sebe navazane veci ... NOPE toho mam v praci akorat, sorry ze jsem neco rikal nekde ... uz mlcim

**Comment by ETNyx** [comment]
Není to tak složitý,.. pokud to tlačíš přes apache a virtualnní hostitele tak pomocí direktivy "AllowOverride None" potlačit .htaccess soubor ve kterým je redirect na https, v souboru index.php zakomentovat include config a pripojení do dtb a dále dvě while smyčky co dotazujou dtb

``` php
<?php
define('VPSFREE', true);

header("Cache-Control: no-cache, must-revalidate"); // HTTP/1.1
header("Expires: Sat, 26 Jul 1997 05:00:00 GMT"); // Date in the past

//require "config.php";
require "lib/db.lib.php";

//$db = new sql_db (DB_HOST, DB_USER, DB_PASS, DB_NAME);
?>
```

``` php
             <span>Distribuce 64bit:</span>
             <select name="distribution" id="distribution">
                <?php
                  //while($tpl = $db->findByColumn("cfg_templates", "templ_supported", "1", "templ_order, templ_label"))
                    //echo '<option value="'.$tpl["templ_id"].'">'.$tpl["templ_label"].'</option>';
                ?>
             </select>

             <span>Preferovaná lokace pro VPS:</span>
             <select name="location" id="location">
                <?php
                    //while($loc = $db->findByColumn("locations", "location_type", "production", "location_id"))
                        //echo '<option value="'.$loc["location_id"].'">Master Internet '.$loc["location_label"].'</option>';
                ?>
             </select>
```

a jeto,.. + prakticky nakonci jsou měřící kódy ga a piwik ty taky odstranit(zakomentovat) nemusíme zanášet naše pokusy do měřících systémů,...

horší je pak dělat nějaký změny v index.php to musíš trošku naslepo,... nicméně by asi bylo nej řešení aby se nemuseli delat takovýhle workaroundy aby někdo do gitu dumpnul tabulky `cfg_templates` a `locations`. Config.php je na ignorlistu tak si každej může udělat vlasní instanci dtb a pujde to i bez uprav

**Comment by encero** [comment]
K náhledu a připomínkám. http://vps-free.x-api.cz/index.php#order

podrobnosti v #17

**Comment by tomassrnka** [comment]
Dakujem vsetkym za nazory a pripomienky, @encero navrh prijaty a je na webe (patri mu osobitna velka vdaka)
