### ISSUE TITLE
slide-who - kdo je za tím vším?

### ISSUE THREAD

**Issue by ETNyx** [vpsfreecz/www.vpsfree.cz#4]
Napadlo mne další možný řešení, kdy by se ty doprovodný texty rozbrazovali po přejetí myší.

na výšku to vyjde zhruba stejne jako když jsou tam jen tři a výška slideru zůstane stejná
![screenshot from 2015-02-24 21 31 52](https://cloud.githubusercontent.com/assets/2624462/6358756/463f0744-bc6e-11e4-897c-512eabf6cfdd.png)

případně k vyzkoušení: https://github.com/ETNyx/www.vpsfree.cz/tree/slider

nechci otevírat pull request, kdyby se to moc nelíbilo ať to moc neplevelíme.

**Comment by petrkrcmar** [comment]
To je perfektní řešení, jsem rozhodně pro něco takového. Díky

**Comment by ETNyx** [comment]
tak další update opět možno vyzkouset ve větvi https://github.com/ETNyx/www.vpsfree.cz/tree/slider

U kontrolek slideru jsem pridal ty popisky, pro mobilni verzi zmizi (+ lepší zobrazení v mobilni verzi)
upravil jsem aktivni plochu sipek, pridal hover effekt pri najetí myší

![screenshot from 2015-02-25 20 53 19](https://cloud.githubusercontent.com/assets/2624462/6379265/32755c18-bd31-11e4-892a-acc841d733b6.png)
![screenshot from 2015-02-25 20 53 54](https://cloud.githubusercontent.com/assets/2624462/6379266/33c0f4e2-bd31-11e4-9212-6e8086a143e5.png)

**Comment by ETNyx** [comment]
Menu zůstává přilepené u horního okraje stránky, js ošetřené odkazy typu # (animace, případné zobrazení správného slidu).

![screenshot from 2015-02-26 19 21 17](https://cloud.githubusercontent.com/assets/2624462/6398583/ddd081a8-bdec-11e4-93f1-e2fe31823db8.png)

viz https://github.com/vpsfreecz/www.vpsfree.cz/pull/6
